n = int(input('Digite aqui um número: '))
print('==='*8)
print('{} x {:2} = {:2}'.format(n, 1, n*1))
print('{} x {:2} = {:2}'.format(2, n, n*2))
print('{} x {:2} = {:2}'.format(3, n, n*3))
print('{} x {:2} = {:2}'.format(4, n, n*4))
print('{} x {:2} = {:2}'.format(5, n, n*5))
print('{} x {:2} = {:2}'.format(6, n, n*6))
print('{} x {:2} = {:2}'.format(7, n, n*7))
print('{} x {:2} = {:2}'.format(8, n, n*8))
print('{} x {:2} = {:2}'.format(9, n, n*9))
print('{} x {} = {}'.format(10, n, n*10))
print('==='*8)
